apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    stage: test
    owner: nikita
spec:
  type: {{ .Values.service.type }}
  selector:
    project: {{ .Release.Name }}
  ports:
   - name: {{ .Release.Name }}-port
     protocol: {{ .Values.service.protocol }}
     port: {{ .Values.service.webAppPort }}  #  Внешний порт, который открыт для клиентов на уровне сервиса
     targetPort: {{ .Values.service.targetPort }} # Внутренний порт, на который перенаправляется трафик внутри пода